### ISSUE TITLE
Password visible in the 'bash history' 

### ISSUE THREAD

**Issue by secufred** [mohlcyber/McAfee-MVISION-EDR-Integrations#1]
would change the  parser.add_argument('--password', '-P', required=True, type=str)
into  parser.add_argument('--password', '-P', required=False, type=str)
adding "from getpass import getpass" in the import section
adding : 
"
    if not args.password:
        args.password=getpass()
"
just after the "args = parser.parse_args()" 

same could apply to some other fields :) (when you want to run it manually it help to reduce the leak of the password in some logs )

**Comment by mohlcyber** [comment]
Hi Secufred, 
yes you are right. I adjusted most of the scripts to use getpass instead of the direct input. 
I think this is the more appropriate way to do.
Thanks again for your support.
Martin
