### ISSUE TITLE
API documentation/support status

### ISSUE THREAD

**Issue by n2N8Z** [mohlcyber/McAfee-MVISION-EDR-Integrations#4]
Is there any documentation for the APIs used in mvision_edr_threats.py  ?
Are the APIs used in mvision_edr_threats.py supported by McAfee, or are they a reverse-engineering of the web dashboard and how the browser interacts with it ?
The authentication used in the script is inconsistent with: https://www.mcafee.com/enterprise/en-us/solutions/mvision/developer-portal.html -> "Understanding MVISION Authorization model"
How does mvision_edr_threats.py fit with https://www.mcafee.com/enterprise/en-us/solutions/mvision/developer-portal.html -> Self Service->API Access Management ?

**Comment by mohlcyber** [comment]
Hi n2N8Z,
apologise for the late response on your comment. All scripts posted here are not supported by McAfee officially and all API's are reverse-engineered. 
McAfee has released MVISION API end of last year that offers official and supported API's.
If you have any questions please let me know.
Many thanks and best regards,
Martin
