### ISSUE TITLE
Getting a few errors when trying to start the mvision_edr_threats.py

### ISSUE THREAD

**Issue by KDF144** [mohlcyber/McAfee-MVISION-EDR-Integrations#5]
I've left out the user and server info. Otherwise we are getting a few errors. 

python3.6 /usr/lib/activity-feeds/mvision_edr_threats.py -R US -U 'User' -P 'Password' -D 'False' -M 5 -L 1000 -S #.#.#.# -SP #
2021-04-16 11:45:17,266;DEBUG;AUTHENTICATION: Successfully authenticated
2021-04-16 11:45:17,537;INFO;SUCCESS: Successful retrieved threats.
2021-04-16 11:46:18,961;ERROR;Error in retrieving edr.get_detections(). Error: 504 - <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

python3.6 /usr/lib/activity-feeds/mvision_edr_threats.py -R US -U 'User' -P 'Password' -D 'True' -M 5 -L 1000 -S #.#.#.# -SP #
2021-04-16 11:52:11,266;DEBUG;AUTHENTICATION: Successfully authenticated
2021-04-16 11:52:11,699;INFO;SUCCESS: Successful retrieved threats.
2021-04-16 11:52:14,724;ERROR;Error in edr.get_trace(). Error: 404 - {"applicationErrorList":[{"code":"AR-811","message":"Empty blamedProcessList","field":null}]}

**Comment by mohlcyber** [comment]
Hi, 

thanks for your message. Could you please check if you use the correct region? Currently three choices are available. US, EU, SY. Looks like this is happens when you didn't select the correct region.
Please let me know if that fixed the issue.

All the best,
Martin

**Comment by synaveen2020** [comment]
Trying the setup

AUTHENTICATION: Successfully authenticated
SUCCESS: Successful retrieved threats.
ERROR: Something went wrong in retrieving trace data. Error: 404 - {"applicationErrorList":[{"code":"AR-811","message":"Empty blamedProcessList","field":null}]}

I suggested them to use SY ( as the region ), and then the result changed, to below, however, no joy with Threat Events !

One of the recent sample runs after updating the region to SY:

python3 /root/edr/threats-monitoring/mvision_edr_threats.py -R SY --user XXXXXX --password XXXXXXXXXX --details True --minutes 700 --limit 10000
2021-04-19 13:30:03,909;DEBUG;AUTHENTICATION: Successfully authenticated
2021-04-19 13:30:03,956;INFO;SUCCESS: Successful retrieved threats.
2021-04-19 13:30:03,956;INFO;{"total": 0, "skipped": 0, "items": 0, "threats": []}

Note : There are threats in the Threat work space and while they are there, we cannot see these events in the syslog.

We are able to get events for “case” passed to the syslog though.

**Comment by mohlcyber** [comment]
Alright great. Looks good. Could you please check the newest version 0.5 of the script. I just changed the time calculation from local time to UTC time. Please let me know if that fixes the issue.

**Comment by arniecommits** [comment]
@synaveen2020 we found an issue with python 3.6 , please use 3.7 or higher , your region should be reflected in the url post login ...

**Comment by KDF144** [comment]
Thanks, We'll try the updated versions script version and python 3.7. I'll let you know the results.

**Comment by mohlcyber** [comment]
I will close the issue on Github for now. I also updated the threats-monitoring script recently (v.0.6). Please makes sure you are using the latest version. If the issue still exists please reopen.
