### ISSUE TITLE
Mvision EDR API URL

### ISSUE THREAD

**Issue by jonathanyaod3** [mohlcyber/McAfee-MVISION-EDR-Integrations#6]
From McAfee Mvision API doc, I can only find this URL "https://api.mvision.mcafee.com/edr/v2". May I know what is different between "api.mvision.mcafee.com/edr/v2" and "https://api.soc.mcafee.com"?

**Comment by mohlcyber** [comment]
Hi, yes sure. 

The first URL you mentioned goes through the MVISION API Gateway and the other one directly to the MVISION EDR service.
The MVISION API - EDR API allows to create new Investigations (official McAfee supported).
The MVISION EDR direct API's allow to interact with MVISION EDR directly - you are able to interact with most of the EDR 
capabilities (not official McAfee supported - community supported).
Hope that clarifies it. If not please let me know.

I will close the issue for now, please reopen if needed.

All the best,
Martin

**Comment by jonathanyaod3** [comment]
Hi Martin,

Thanks a lot for your prompt response. May I confirm my understanding to your answer?
1.  "https://api.mvision.mcafee.com/edr/v2" goes through MV API gateway and is officially supported by McAfee. However, the only API I found is to create new investigations. BTW, I find it doesn't work recently(stop working before 1 or 2 months). API returns "200 ok", but new investigation is not created at all, and it only displays some updates on previously created investigation. 
2. "https://api.soc.mcafee.com" goes to MV EDR service directly without going through MV API gateway, and I can interact with most of the EDR capabilities via this URL, However, it is NOT officially supported by McAfee, only community supported. I think that is why we cannot find any document about APIs of this URL. Would you share more communicty supported EDR APIs besides threat detections and traces?

Thanks again and regards..

Jonathan

**Comment by mohlcyber** [comment]
Hi Jonathan, 

yes spot on. Absolutely right. Sure happy to add more direct EDR APIs. Do you have any specific use cases / API calls in mind to add? Happy to look into it and to add it. This is also how the repository actually started. 

All the best,

Martin

**Comment by jonathanyaod3** [comment]
Hi Martin,

Very appreciate your fast response. I want to quarantine/unquarantine a
device, and stop a process just as what I can do on UI. In fact, I can
scratch the APIs from the browser developer tool, but I cannot accomplish
that with only device hostname or IP address and I have to check related
host id from specific threat(s).

Besides that, is there a EDR API to get investigation information? By the
way, do you find the MVISION EDR investigation creation API issue? I have
opened a service ticket to McAfee, but I haven't got feedback for
almost two months.

[image: image.png]

Thanks and have a great one..

Jonathan

**Comment by mohlcyber** [comment]
Hi Jonathan,

sure i can help with that. Usually you have to run a RTS first to execute reactions. Similar like the examples here:
https://github.com/mohlcyber/McAfee-MVISION-EDR-Integrations/tree/master/real-time-search-reaction

Anyhow Quarantine, Unquarantine and Stop Process can be done directly from a threat detection. I will upload a script in the coming days to include that. Will keep you posted.

Regards your other questions - actually there are some API's to get Investigation information. Either list them all or via Investigation ID you can get information of the Investigation itself. There are also some links included to get information about the findings (based on the investigation guides), artefacts, etc.

All the best,
Martin

**Comment by jonathanyaod3** [comment]
Hi Martin,

Thank you so much.

Besides RTS, can we trigger remediation actions via threat-actions? I am
searching if we can take quarantine/unquarantine/stop process actions on
hosts via this URL:
https://api.soc.mcafee.com/remediation/api/v1/actions/threat-actions, just
like what we can do on EDR UI. But my credential scope looks limited and
API call returns "403 Forbidden".

B.R.

Jonathan

**Comment by jonathanyaod3** [comment]
Hi Martin,

I can do RTS right now, and I am going to test some contain actions, such
as quarantine/unquarantine hosts, may I know where I can find import
arguments for such reaction commands?
Many thanks

{
            "hidden": false,
            "description": "Quarantines the host",
            "classification": "CONTAINMENT",
            "type": "BUILTIN",
            "timeout": 60,
            "internalName": "quarantineHost",
            "remediation": false,
            "task": "REACTION",
            "availableForTrigger": true,
            "name": "QuarantineHost",
            "arguments": [],
            "id": "22",
            "availableOffline": true,
            "chainedReactions": []
        },

**Comment by seb219** [comment]
Hi Martin,

We would like to use reactions directly from threat detection as you have mentionned previously.
We did not find the correct method.

We would appreciate if you could give us this information.

Best Regards,

Sebastien
