### ISSUE TITLE
Quarantine device syntax error in comment

### ISSUE THREAD

**Issue by ondromalik** [mohlcyber/McAfee-MVISION-EDR-Integrations#8]
Hi Martin,

I have noticed, that you have a syntax error in comment in file threats-monitoring/mvision_edr_threats_reaction.py line 207.
The correct action that quarantines the device is "QuarantineHost", not "Quarantine". 
If you use "Quarantine", you get - Error: 400 - {"code":"REM-10002","message":"Invalid parameter","field":"action"}.

It is just a detail, but I have spent some time figuring it out.
Thank you for your work!
Ondrej

**Comment by mohlcyber** [comment]
Hi Ondrej, thanks for pointing this out. As part of the authentication change i updated the script with the correct reaction arguments.
