### ISSUE TITLE
How to use this tool with API token?

### ISSUE THREAD

**Issue by ninhhv** [mohlcyber/McAfee-MVISION-EDR-Integrations#9]
With enforcement MFA, only way to authen by API token, how I can do for this case? Help me, please!

**Comment by mohlcyber** [comment]
Hi Ninhhv,

all scripts got updated a couple of weeks ago to use the new client credential based authentication. 
In the past the user based authentication required a service account that did not support MFA.
 
The process to generate client credentials is posted here:
https://github.com/mohlcyber/McAfee-MVISION-EDR-Integrations/blob/master/README.md

If you have any questions or need further details please let me know.

All the best,
Martin

**Comment by ninhhv** [comment]
hi @mohlcyber , thank for your feedback! But on the "McAfee MVISION EDR Activity Feed" still use "**User** and **Password**" and I want to using it with client credential based authentication, Can you help me?

**Comment by mohlcyber** [comment]
Hi Ninhhv,
you are right. The dxlstreaming libraries needed to be adjusted. The dxlstreaming libraries as well as the activity feeds have been updated. 

https://github.com/mcafee-enterprise/mvision-edr-activity-feed
https://github.com/opendxl/opendxl-streaming-client-python

I also updated my Activity Feed version here:
https://github.com/mohlcyber/McAfee-MVISION-EDR-Integrations/tree/master/activity-feeds

If you have any questions or need further details please let me know.

All the best,
Martin
